* GENERATED by tools/tiasnd.py - do not edit
* TIA channel output at AUDF=0 for each AUDC, as run lengths in audio
* clocks (31.4 kHz) starting with a high run, 0-terminated.  AUDC 0 and
* 11 are a constant level (silent) and have no pattern.

SndPat1           db    4,3,1,2,2,1,1,1,0
SndPat2           db    31,13,18,13,62,49,13,31,31,18,13,18,62,44,18,31,0
SndPat3           db    1,3,4,7,1,3,7,3,2,1,6,6,2,2,4,5,3,2,6,6,1,3,3,2,5,3,7,3,4,3,2,2
                  db    2,5,9,3,1,5,3,1,2,2,11,5,1,5,3,1,1,2,12,5,1,2,5,2,1,1,12,6,1,2,5,1
                  db    2,1,10,6,3,2,2,4,1,2,6,10,1,4,2,1,4,1,6,10,2,4,2,1,1,4,5,9,3,3,4,1
                  db    1,1,8,5,5,5,4,1,1,1,8,4,2,8,3,3,1,1,7,4,2,7,5,1,3,1,7,4,1,4,8,2,0
SndPat4           db    1,1,0
SndPat5           db    1,1,0
SndPat6           db    18,13,0
SndPat7           db    2,1,3,1,1,1,1,4,1,2,1,1,2,2,5,3,0
SndPat8           db    1,1,1,2,1,1,1,1,4,2,1,1,3,1,3,6,3,2,3,1,1,2,1,2,4,1,1,1,3,1,1,1
                  db    1,3,1,2,1,4,2,2,3,4,1,1,4,1,2,1,2,2,2,1,1,4,3,1,4,4,9,5,4,1,5,3
                  db    1,1,3,2,2,2,1,5,1,2,1,1,1,2,3,1,2,1,1,3,4,2,5,2,2,1,2,3,1,1,1,1
                  db    1,2,1,3,3,3,2,1,2,1,1,1,1,1,3,3,1,2,2,3,1,3,1,8,1,4,1,3,2,4,1,2
                  db    3,2,1,1,1,1,1,1,2,4,2,1,4,1,1,2,2,1,3,2,1,3,1,1,1,4,1,1,1,1,2,1
                  db    1,2,6,1,2,2,1,2,1,2,1,1,2,1,6,2,1,2,2,1,1,1,1,2,2,2,2,7,2,3,2,2
                  db    1,1,1,3,2,1,1,2,1,1,7,1,1,3,1,1,2,3,3,1,1,1,2,2,1,1,2,2,4,3,5,1
                  db    3,1,1,5,2,1,1,1,2,1,2,1,3,1,2,5,1,1,2,1,1,1,5,1,1,1,1,1,1,1,1,6,0
SndPat9           db    1,4,1,2,1,1,2,2,5,3,2,1,3,1,1,1,0
SndPatA           db    18,13,0
SndPatC           db    3,3,0
SndPatD           db    3,3,0
SndPatE           db    49,44,0
SndPatF           db    6,3,6,4,9,6,5,6,4,5,10,5,3,7,4,10,0

SndPatLo          db    <SndPat4,<SndPat1,<SndPat2,<SndPat3,<SndPat4,<SndPat5,<SndPat6,<SndPat7,<SndPat8,<SndPat9,<SndPatA,<SndPat4,<SndPatC,<SndPatD,<SndPatE,<SndPatF
SndPatHi          db    >SndPat4,>SndPat1,>SndPat2,>SndPat3,>SndPat4,>SndPat5,>SndPat6,>SndPat7,>SndPat8,>SndPat9,>SndPatA,>SndPat4,>SndPatC,>SndPatD,>SndPatE,>SndPatF
SndMaxRun         db    0,4,62,12,1,1,18,5,9,5,18,0,3,3,49,10   ; 0 = silent
