* GENERATED by tools/wintune.py - do not edit
* The win tune for PlayWinTune: length in 256-pass units, then the
* two voices' phase increments (0 = silent).  Length 0 ends it.
WinSong
                  db    10,247,7,252,3
                  db    1,0,0,0,0
                  db    10,247,7,252,3
                  db    1,0,0,0,0
                  db    10,247,7,252,3
                  db    1,0,0,0,0
                  db    31,162,10,84,5
                  db    1,0,0,0,0
                  db    10,101,13,162,10
                  db    1,0,0,0,0
                  db    10,239,11,247,7
                  db    1,0,0,0,0
                  db    10,101,13,162,10
                  db    1,0,0,0,0
                  db    31,238,15,168,10
                  db    1,0,0,0,0
                  db    10,49,14,25,7
                  db    1,0,0,0,0
                  db    10,101,13,162,10
                  db    1,0,0,0,0
                  db    10,239,11,247,7
                  db    1,0,0,0,0
                  db    10,162,10,81,5
                  db    1,0,0,0,0
                  db    4,81,5,0,0
                  db    1,0,0,0,0
                  db    4,179,6,0,0
                  db    1,0,0,0,0
                  db    4,247,7,0,0
                  db    1,0,0,0,0
                  db    4,162,10,0,0
                  db    1,0,0,0,0
                  db    4,101,13,0,0
                  db    1,0,0,0,0
                  db    4,238,15,0,0
                  db    1,0,0,0,0
                  db    20,68,21,248,15
                  db    1,0,0,0,0
                  db    41,68,21,170,10
                  db    1,0,0,0,0
                  db    0
