* GENERATED by tools/gen_gfx.py from ref/Adventure.txt - do not edit

* Room data: gfx ptr, color, B&W color, ctrl (b7 left thin wall, b6 right,
*            b2 PF priority), room above, left, down, right ($80|n -> RoomDiffs)
RoomDataTable
                  da    NumberRoom
                  hex   660a2100000000
                  da    BelowYellowCastle
                  hex   d80aa108028003
                  da    BelowYellowCastle
                  hex   c80a2111038301
                  da    LeftOfName
                  hex   e80a6106018602
                  da    BlueMazeTop
                  hex   860a2110050706
                  da    BlueMaze1
                  hex   860a211d060804
                  da    BlueMazeBottom
                  hex   860a2107040305
                  da    BlueMazeCenter
                  hex   860a2104080608
                  da    BlueMazeEntry
                  hex   860a2105070107
                  da    MazeMiddle
                  hex   0808250a0a0b0a
                  da    MazeEntry
                  hex   08082503090909
                  da    MazeSide
                  hex   080825090c1c0d
                  da    SideCorridor
                  hex   980a611c0d1d0b
                  da    SideCorridor
                  hex   b80aa10f0b0e0c
                  da    TopEntryRoom
                  hex   a80a210d100f10
                  da    CastleDef
                  hex   0c0c210e0f0d0f
                  da    CastleDef
                  hex   000221011c041c
                  da    CastleDef
                  hex   1a0a2106030201
                  da    NumberRoom
                  hex   1a0a2112121212
                  da    BlackMaze1
                  hex   08082515141516
                  da    BlackMaze2
                  hex   08082416151613
                  da    BlackMaze3
                  hex   08082413161314
                  da    BlackMazeEntry
                  hex   08082514131b15
                  da    RedMaze1
                  hex   360a2119181918
                  da    RedMazeTop
                  hex   360a211a171a17
                  da    RedMazeBottom
                  hex   360a21171a171a
                  da    WhiteCastleEntry
                  hex   360a2118191819
                  da    TwoExitRoom
                  hex   360a2189898989
                  da    NumberRoom
                  hex   660a211d078c08
                  da    TopEntryRoom
                  hex   360a218f011003
                  da    BelowYellowCastle
                  hex   660a2106010603
RoomDiffs          hex   100f0f0511111d0a0a1c16161b0c0c03
                   hex   0c0c

NumberRoom         hex   f0ffff
                   hex   300000
                   hex   300000
                   hex   300000
                   hex   300000
                   hex   300000
                   hex   f0ff0f
BelowYellowCastle  hex   f0ff0f
                   hex   000000
                   hex   000000
                   hex   000000
                   hex   000000
                   hex   000000
                   hex   f0ffff
LeftOfName         hex   f0ffff
                   hex   000000
                   hex   000000
                   hex   000000
                   hex   000000
                   hex   000000
                   hex   f0ff0f
BlueMazeTop        hex   f0ff0f
                   hex   000c0c
                   hex   f00c3c
                   hex   f00c00
                   hex   f0ff3f
                   hex   003030
                   hex   f0333f
BlueMaze1          hex   f0ffff
                   hex   000000
                   hex   f0fcff
                   hex   f000c0
                   hex   f03fcf
                   hex   0030cc
                   hex   f0f3cc
BlueMazeBottom     hex   f0f30c
                   hex   00300c
                   hex   f03f0f
                   hex   f00000
                   hex   f0f000
                   hex   003000
                   hex   f0ffff
BlueMazeCenter     hex   f0333f
                   hex   00303c
                   hex   f0ff3c
                   hex   00033c
                   hex   f0333c
                   hex   00330c
                   hex   f0f30c
BlueMazeEntry      hex   f0f3cc
                   hex   00330c
                   hex   f033fc
                   hex   003300
                   hex   f0f3ff
                   hex   000000
                   hex   f0ff0f
MazeMiddle         hex   f0ffcc
                   hex   0000cc
                   hex   f003cf
                   hex   000300
                   hex   f0f3fc
                   hex   00330c
                   hex   f033cc
MazeEntry          hex   f0ff0f
                   hex   003000
                   hex   f030ff
                   hex   0030c0
                   hex   f0f3c0
                   hex   0003c0
                   hex   f0ffcc
MazeSide           hex   f033cc
                   hex   0030cc
                   hex   003fcf
                   hex   0000c0
                   hex   003fc3
                   hex   0030c0
                   hex   f0ffff
SideCorridor       hex   f0ff0f
                   hex   000000
                   hex   000000
                   hex   000000
                   hex   000000
                   hex   000000
                   hex   f0ff0f
TopEntryRoom       hex   f0ff0f
                   hex   300000
                   hex   300000
                   hex   300000
                   hex   300000
                   hex   300000
                   hex   f0ffff
CastleDef          hex   f0fe15
                   hex   30031f
                   hex   3003ff
                   hex   3000ff
                   hex   30003f
                   hex   300000
                   hex   f0ff0f
BlackMaze1         hex   f0f0ff
                   hex   000003
                   hex   f0ff03
                   hex   000000
                   hex   303fff
                   hex   003000
                   hex   f0f0ff
BlackMaze2         hex   f0ffff
                   hex   0000c0
                   hex   f0ffcf
                   hex   00000c
                   hex   f00fff
                   hex   000fc0
                   hex   30cfcc
BlackMaze3         hex   f0f0ff
                   hex   300000
                   hex   303fff
                   hex   003000
                   hex   f0f0ff
                   hex   300003
                   hex   f0f0ff
BlackMazeEntry     hex   30cfcc
                   hex   00c0cc
                   hex   f0ff0f
                   hex   000000
                   hex   f0ff0f
                   hex   000000
                   hex   f0ff0f
RedMaze1           hex   f0ffff
                   hex   000000
                   hex   f0ff0f
                   hex   00000c
                   hex   f0ff0c
                   hex   f003cc
                   hex   f033cf
RedMazeTop         hex   f0ffff
                   hex   0000c0
                   hex   f0ffcf
                   hex   0000cc
                   hex   f033ff
                   hex   f03300
                   hex   f03f0c
RedMazeBottom      hex   f033cf
                   hex   f03000
                   hex   f033ff
                   hex   003300
                   hex   f0ff00
                   hex   000000
                   hex   f0ff0f
WhiteCastleEntry   hex   f03f0c
                   hex   f0000c
                   hex   f0ff0f
                   hex   003000
                   hex   f03000
                   hex   003000
                   hex   f0ff0f
TwoExitRoom        hex   f0ff0f
                   hex   300000
                   hex   300000
                   hex   300000
                   hex   300000
                   hex   300000
                   hex   f0ff0f

* Object table (index = object number = n*9):
*  +0 ZP addr of dynamic data (room,x,y[,move,state]), +1 unused
*  +2 ZP addr of current state byte, +3 unused, +4/+5 -> state list,
*  +6 color, +7 B&W color, +8 size ($07 = quad width)
Store1             db    $d9,0,$6f,0
                  da    SurroundStates
                  hex   280c07    ; 00 Surround
Store2             =     Store1+1
Store3             =     Store1+2
Store4             =     Store1+3
Store5             =     Store1+4
Store6             =     Store1+5
Store7             =     Store1+6
Store8             =     Store1+7
Store9             =     Store1+8
                   db    $60,0,$c8,0
                  da    PortStates
                  hex   000000    ; 01 Port1
                   db    $63,0,$c9,0
                  da    PortStates
                  hex   000000    ; 02 Port2
                   db    $66,0,$ca,0
                  da    PortStates
                  hex   000000    ; 03 Port3
                   db    $69,0,$6f,0
                  da    AuthorStates
                  hex   cb0000    ; 04 Author
                   db    $6c,0,$dd,0
                  da    NumberStates
                  hex   c80000    ; 05 Number
                   db    $a4,0,$a8,0
                  da    DragonStates
                  hex   360e00    ; 06 RedDragon
                   db    $a9,0,$ad,0
                  da    DragonStates
                  hex   1a0600    ; 07 YelDragon
                   db    $ae,0,$b2,0
                  da    DragonStates
                  hex   c80000    ; 08 GrnDragon
                   db    $b6,0,$6f,0
                  da    SwordStates
                  hex   1a0600    ; 09 Sword
                   db    $bc,0,$6f,0
                  da    BridgeStates
                  hex   660207    ; 10 Bridge
                   db    $bf,0,$6f,0
                  da    KeyStates
                  hex   1a0600    ; 11 YelKey
                   db    $c2,0,$6f,0
                  da    KeyStates
                  hex   0e0e00    ; 12 WhtKey
                   db    $c5,0,$6f,0
                  da    KeyStates
                  hex   000000    ; 13 BlkKey
                   db    $cb,0,$cf,0
                  da    BatStates
                  hex   000000    ; 14 Bat
                   db    $a1,0,$6f,0
                  da    DotStates
                  hex   080800    ; 15 Dot
                   db    $b9,0,$6f,0
                  da    ChaliceStates
                  hex   cb0600    ; 16 Chalice
                   db    $b3,0,$6f,0
                  da    MagnetStates
                  hex   000600    ; 17 Magnet
                   db    $bc,0,$6f,0
                  da    NullStates
                  hex   000000    ; 18 Null

* State lists: state value, sprite id, 0 (3 bytes/entry, last state $ff)
SurroundStates
                  db    $ff,8,0        ; GfxSurround
PortStates
                  db    $04,7,0        ; GfxPort07
                  db    $08,6,0        ; GfxPort06
                  db    $0c,5,0        ; GfxPort05
                  db    $10,4,0        ; GfxPort04
                  db    $14,3,0        ; GfxPort03
                  db    $18,2,0        ; GfxPort02
                  db    $1c,1,0        ; GfxPort01
                  db    $20,2,0        ; GfxPort02
                  db    $24,3,0        ; GfxPort03
                  db    $28,4,0        ; GfxPort04
                  db    $2c,5,0        ; GfxPort05
                  db    $30,6,0        ; GfxPort06
                  db    $ff,7,0        ; GfxPort07
AuthorStates
                  db    $ff,21,0        ; GfxAuthor
NumberStates
                  db    $01,10,0        ; GfxNum1
                  db    $03,11,0        ; GfxNum2
                  db    $ff,12,0        ; GfxNum3
DragonStates
                  db    $00,16,0        ; GfxDrag0
                  db    $01,18,0        ; GfxDrag2
                  db    $02,16,0        ; GfxDrag0
                  db    $ff,17,0        ; GfxDrag1
SwordStates
                  db    $ff,19,0        ; GfxSword
BridgeStates
                  db    $ff,9,0        ; GfxBridge
KeyStates
                  db    $ff,13,0        ; GfxKey
BatStates
                  db    $03,14,0        ; GfxBat1
                  db    $ff,15,0        ; GfxBat2
DotStates
                  db    $ff,20,0        ; GfxDot
ChaliceStates
                  db    $ff,22,0        ; GfxChalice
MagnetStates
                  db    $ff,23,0        ; GfxMagnet
NullStates
                  db    $ff,0,0        ; GfxNull

Loc_1              hex   b9131aa4011da9011dae011db6011dbc
                   hex   011dbf011dc20116c50112cb011db301
                   hex   1d
Loc_4             da    Game1Objects,Game2Objects,Game2Objects
Game1Objects       hex   1551120e5020000001502000001d5020
                   hex   00001b80201220201c30200429371120
                   hex   400e20401d20401c1c1c1a2020000078
                   hex   00
Game2Objects       hex   155112145020a000195020a000045020
                   hex   a0000e80201120201430200b40400920
                   hex   400620401920401c1c1c022020900078
                   hex   00
ReadStick_3        hex   00c030
RedDragMatrix      hex   b6a4a48aa4b9a4c200
YelDragMatrix      hex   b6a9bfa9a98aa9b900
GreenDragMatrix    hex   b6aeae8aaeb9aebcaeb3aec500
DragonDiff         hex   d0e8f0f6f0f6
BatMatrix          hex   cbb9cbb6cbbccbbfcbc2cbc5cba4cba9
                   hex   cbaecbb300
PortOffsets        hex   09121b
KeyOffsets         hex   636c75
EntryRoomOffsets   hex   121a1b
CastleRoomOffsets  hex   110f10
MagnetMatrix       hex   bfb3c2b3c5b3b6b3bcb3b9b300
Loc_2             =     Loc_1+1
Loc_3             =     Loc_1+2
Loc_5             =     Loc_4+1
ZPConsts           hex   114d310f4d31104d311e506900504000
ZPConstsLen       =     16
