* GENERATED by tools/gen_gfx.py from ref/Adventure.txt - do not edit

SprHeight         db    0,16,14,12,10,8,6,4,32,24,7,7,7,3,7,11,20,22,17,5,1,95,9,8
SprQuad           db    0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
SprRowsL          db    <GfxNull,<GfxPort01,<GfxPort02,<GfxPort03,<GfxPort04,<GfxPort05,<GfxPort06,<GfxPort07,<GfxSurround,<GfxBridge,<GfxNum1,<GfxNum2,<GfxNum3,<GfxKey,<GfxBat1,<GfxBat2,<GfxDrag0,<GfxDrag1,<GfxDrag2,<GfxSword,<GfxDot,<GfxAuthor,<GfxChalice,<GfxMagnet
SprRowsH          db    >GfxNull,>GfxPort01,>GfxPort02,>GfxPort03,>GfxPort04,>GfxPort05,>GfxPort06,>GfxPort07,>GfxSurround,>GfxBridge,>GfxNum1,>GfxNum2,>GfxNum3,>GfxKey,>GfxBat1,>GfxBat2,>GfxDrag0,>GfxDrag1,>GfxDrag2,>GfxSword,>GfxDot,>GfxAuthor,>GfxChalice,>GfxMagnet
GfxNull            =     *
GfxPort01          hex   feaafeaafeaafeaafeaafeaafeaafeaa
GfxPort02          hex   feaafeaafeaafeaafeaafeaafeaa
GfxPort03          hex   feaafeaafeaafeaafeaafeaa
GfxPort04          hex   feaafeaafeaafeaafeaa
GfxPort05          hex   feaafeaafeaafeaa
GfxPort06          hex   feaafeaafeaa
GfxPort07          hex   feaafeaa
GfxSurround        hex   ffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffff
GfxBridge          hex   c3c3c3c3424242424242424242424242
                   hex   42424242c3c3c3c3
GfxNum1            hex   040c040404040e
GfxNum2            hex   0e11010204081f
GfxNum3            hex   0e11010601110e
GfxKey             hex   07fda7
GfxBat1            hex   8181c3c3ff5a66
GfxBat2            hex   018001803c5a66c3818181
GfxDrag0           hex   060ff3fe0e04041e3f7fe3c3c3c7ff3c
                   hex   088fe13f
GfxDrag1           hex   8040261f0b0e1e24448e1e3f7f7f7f7f
                   hex   3e1c08f880e0
GfxDrag2           hex   0c0c0c0e1b7fce80fcfefe7e78206e42
                   hex   7e
GfxSword           hex   2040ff4020
GfxDot             hex   80
GfxAuthor          hex   f0808080f40487e5878005e5a7e187e0
                   hex   01e0a0f00140e040404001e0a0e080e0
                   hex   012020e0a0e001010188a8a8a8f801e0
                   hex   a0f00180e08f890f8ae9808e0aeea0e8
                   hex   88ee0a8ee0a4a40480080e0a0a800e0a
                   hex   0e080e80040e04040480040e040404
GfxChalice         hex   8181c37e7e3c18187e
GfxMagnet          hex   3c7ee7c3c3c3c3c3
