"""Generate the data files for both targets from the 2600 reference listing.

  src/core/data.s      room table, room bitmaps, object table, state lists,
                       initial object positions, matrices, misc tables
  src/core/gfx2600.s   1-bit sprite rows (height table + row data), used by
                       the software collision code on both targets
  src/a2/gfxhgr.s      HGR sprites, 2 px per clock, 4 x-phases (shift 0/2/4/6 px)
  src/gs/gfxshr.s      SHR sprites, 1 byte per clock ($FF = set)

Object numbers, state values, coordinate conventions are all kept identical
to the 2600 ROM so the game logic can be checked against the disassembly."""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
import rom2600

ROOT = os.path.join(os.path.dirname(__file__), '..')
rom, L = rom2600.load()
def R(addr, n=1):
    o = addr - 0xF000
    return rom[o:o+n]

# ---------------------------------------------------------------- sprites
# id -> label.  Order matters only for the tables; Null must be 0.
SPRITES = ['GfxNull', 'GfxPort01', 'GfxPort02', 'GfxPort03', 'GfxPort04',
           'GfxPort05', 'GfxPort06', 'GfxPort07', 'GfxSurround', 'GfxBridge',
           'GfxNum1', 'GfxNum2', 'GfxNum3', 'GfxKey', 'GfxBat1', 'GfxBat2',
           'GfxDrag0', 'GfxDrag1', 'GfxDrag2', 'GfxSword', 'GfxDot',
           'GfxAuthor', 'GfxChalice', 'GfxMagnet']
QUAD = {'GfxSurround', 'GfxBridge'}          # NUSIZ $07: 4 clocks per bit
SPRID = {name: i for i, name in enumerate(SPRITES)}

def sprite_rows(name):
    a = L[name]
    rows = []
    while rom[a - 0xF000] != 0:
        rows.append(rom[a - 0xF000]); a += 1
    return rows

def hexline(label, data, per=16):
    out = []
    for i in range(0, len(data), per):
        lab = label if i == 0 else ''
        out.append('%-18s hex   %s' % (lab, ''.join('%02x' % b for b in data[i:i+per])))
    if not data:
        out.append('%-18s =     *' % label)
    return out

HDR = '* GENERATED by tools/gen_gfx.py from ref/Adventure.txt - do not edit\n'

# ------------------------------------------------------------ gfx2600.s
out = [HDR]
out.append('SprHeight         db    ' + ','.join(str(len(sprite_rows(s))) for s in SPRITES))
out.append('SprQuad           db    ' + ','.join('1' if s in QUAD else '0' for s in SPRITES))
out.append('SprRowsL          db    ' + ','.join('<%s' % s for s in SPRITES))
out.append('SprRowsH          db    ' + ','.join('>%s' % s for s in SPRITES))
for s in SPRITES:
    out += hexline(s, sprite_rows(s))
open(os.path.join(ROOT, 'src/core/gfx2600.s'), 'w').write('\n'.join(out) + '\n')

# ------------------------------------------------------------ gfxhgr.s
# One colour clock is 4/7 of an HGR byte, so a sprite bit is 1.75 px and
# eight of them are 14 px - the same scale as the playfield, where one
# playfield pixel (4 clocks) is exactly one 7-pixel byte.  Pixel p of a
# row therefore belongs to clock p*4/7.  A quad bit is 4 clocks = 7 px.
# Clock x starts at pixel 7x/4, i.e. byte x/4 offset PHASEPX[x&3].
# HGR byte: bit0 = leftmost px, bit7 unused (colour hi-bit added at blit).
PHASEPX = [0, 1, 3, 5]
def hgr_row(bits, quad, phase):
    bit = lambda b: (bits >> (7 - b)) & 1
    if quad:
        px = [bit(b) for b in range(8) for _ in range(7)]
    else:
        px = [bit((p * 4) // 7) for p in range(14)]
    px = [0] * PHASEPX[phase] + px
    nbytes = 8 if quad else 3
    px += [0] * (nbytes * 7 - len(px))
    return [sum(px[i*7 + k] << k for k in range(7)) for i in range(nbytes)]

out = [HDR, '* layout per sprite: rows*bpr bytes for phase 0, then phase 1,2,3']
out.append('SprHgrBpr         db    ' + ','.join('8' if s in QUAD else '3' for s in SPRITES))
# A sprite whose every row is solid draws the same pixels wherever it is,
# so when it only shifts a little the renderer can repaint just the edges.
out.append('SprSolid          db    ' + ','.join(
    '1' if (s in QUAD and sprite_rows(s) and all(r == 0xff for r in sprite_rows(s))) else '0'
    for s in SPRITES))
out.append('SprHgrL           db    ' + ','.join('<H%s' % s for s in SPRITES))
out.append('SprHgrH           db    ' + ','.join('>H%s' % s for s in SPRITES))
for s in SPRITES:
    rows = sprite_rows(s)
    data = []
    # A quad-width bit is 4 colour clocks = exactly one 7-pixel HGR byte,
    # so quad sprites sit on the byte grid and need no pre-shifted phases.
    for phase in ([0] if s in QUAD else range(4)):
        for r in rows:
            data += hgr_row(r, s in QUAD, phase)
    out += hexline('H' + s, data)
open(os.path.join(ROOT, 'src/a2/gfxhgr.s'), 'w').write('\n'.join(out) + '\n')

# ------------------------------------------------------------ gfxshr.s
out = [HDR, '* one byte per clock ($ff = pixel on), 8 or 32 bytes per row']
out.append('SprShrBpr         db    ' + ','.join('32' if s in QUAD else '8' for s in SPRITES))
out.append('SprShrL           db    ' + ','.join('<S%s' % s for s in SPRITES))
out.append('SprShrH           db    ' + ','.join('>S%s' % s for s in SPRITES))
for s in SPRITES:
    data = []
    if True:
        for r in sprite_rows(s):
            for b in range(8):
                on = (r >> (7 - b)) & 1
                data += [0xff if on else 0] * (4 if s in QUAD else 1)
    out += hexline('S' + s, data, 32)
open(os.path.join(ROOT, 'src/gs/gfxshr.s'), 'w').write('\n'.join(out) + '\n')

# --------------------------------------------------------------- data.s
# ZP copies of ROM-resident "dynamic" object data and state bytes so the
# core can address every object with direct-page indexing (see zp.s).
ZP_REMAP = {L['PortInfo1']: 0x60, L['PortInfo2']: 0x63, L['PortInfo3']: 0x66,
            L['AuthorInfo']: 0x69, L['NumberInfo']: 0x6c}
ZERO_STATE = 0x6f      # replaces every ROM-resident xxxCurr byte (always 0)

out = [HDR]
# room graphics: 21 bytes per room, read sequentially like the 2600 kernel does
room_labels = []
for room in range(31):                # 00-1e; 1e is the secret room
    a = L['RoomDataTable'] + room * 9
    ptr = R(a, 2); ptr = ptr[0] | ptr[1] << 8
    name = [k for k, v in L.items() if v == ptr and not k.startswith('@')][0]
    room_labels.append((name, list(R(a + 2, 7))))
out.append('* Room data: gfx ptr, color, B&W color, ctrl (b7 left thin wall, b6 right,')
out.append('*            b2 PF priority), room above, left, down, right ($80|n -> RoomDiffs)')
out.append('RoomDataTable')
for name, rest in room_labels:
    out.append('                  da    %s' % name)
    out.append('                  hex   %s' % ''.join('%02x' % b for b in rest))
out += hexline('RoomDiffs', list(R(L['RoomDiffs'], 18)))
out.append('')
seen = set()
for name, _ in room_labels:
    if name in seen: continue
    seen.add(name)
    out += hexline(name, list(R(L[name], 21)), 3)
out.append('')

# object table, 9 bytes per object, indexed by object number (n*9)
out.append('* Object table (index = object number = n*9):')
out.append('*  +0 ZP addr of dynamic data (room,x,y[,move,state]), +1 unused')
out.append('*  +2 ZP addr of current state byte, +3 unused, +4/+5 -> state list,')
out.append('*  +6 color, +7 B&W color, +8 size ($07 = quad width)')
names = ['Surround', 'Port1', 'Port2', 'Port3', 'Author', 'Number', 'RedDragon',
         'YelDragon', 'GrnDragon', 'Sword', 'Bridge', 'YelKey', 'WhtKey', 'BlkKey',
         'Bat', 'Dot', 'Chalice', 'Magnet', 'Null']
states_of = {}
for i, nm in enumerate(names):
    a = L['Store1'] + i * 9
    e = R(a, 9)
    dyn = e[0] | e[1] << 8
    cur = e[2] | e[3] << 8
    st = e[4] | e[5] << 8
    dyn = ZP_REMAP.get(dyn, dyn)
    if cur >= 0xF000: cur = ZERO_STATE
    assert dyn < 0x100 and cur < 0x100
    stname = [k for k, v in L.items() if v == st][0]
    states_of[stname] = st
    lab = 'Store1' if i == 0 else ''
    out.append('%-18s db    $%02x,0,$%02x,0' % (lab, dyn, cur))
    out.append('                  da    %s' % stname)
    out.append('                  hex   %02x%02x%02x    ; %02d %s' % (e[6], e[7], e[8], i, nm))
    if i == 0:
        for k in range(2, 10):
            out.append('%-18s =     Store1+%d' % ('Store%d' % k, k - 1))
out.append('')
# state lists: (state, sprite id, 0) triples, terminated like the ROM by the
# $ff catch-all entry
out.append('* State lists: state value, sprite id, 0 (3 bytes/entry, last state $ff)')
for stname, a in states_of.items():
    out.append(stname)
    while True:
        s = rom[a - 0xF000]; g = rom[a - 0xF000 + 1] | rom[a - 0xF000 + 2] << 8
        gname = [k for k, v in L.items() if v == g][0]
        out.append('                  db    $%02x,%d,0        ; %s' % (s, SPRID[gname], gname))
        a += 3
        if s == 0xff: break
out.append('')
for lab, n in [('Loc_1', 33), ('Loc_4', 6), ('Game1Objects', 49), ('Game2Objects', 49),
               ('ReadStick_3', 3), ('RedDragMatrix', 9), ('YelDragMatrix', 9),
               ('GreenDragMatrix', 13), ('DragonDiff', 6), ('BatMatrix', 21),
               ('PortOffsets', 3), ('KeyOffsets', 3), ('EntryRoomOffsets', 3),
               ('CastleRoomOffsets', 3), ('MagnetMatrix', 13)]:
    out += hexline(lab, list(R(L[lab], n)))
out.append('Loc_2             =     Loc_1+1')
out.append('Loc_3             =     Loc_1+2')
out.append('Loc_5             =     Loc_4+1')
# Loc_4 holds ROM pointers to Game1Objects/Game2Objects: emit properly
i = out.index([l for l in out if l.startswith('Loc_4 ')][0])
out[i] = 'Loc_4             da    Game1Objects,Game2Objects,Game2Objects'
# ZP constant block initial values (PortInfo1-3, AuthorInfo, NumberInfo, zero)
consts = list(R(L['PortInfo1'], 9)) + list(R(L['AuthorInfo'], 3)) + list(R(L['NumberInfo'], 3)) + [0]
out += hexline('ZPConsts', consts)
out.append('ZPConstsLen       =     %d' % len(consts))
open(os.path.join(ROOT, 'src/core/data.s'), 'w').write('\n'.join(out) + '\n')
print('ok: %d sprites, %d rooms' % (len(SPRITES), len(room_labels)))

# ---- src/gs/pal2600.s : 2600 NTSC colour byte -> IIgs $0RGB ----------
import math
GRAY = [0x00, 0x40, 0x6C, 0x90, 0xB0, 0xC8, 0xDC, 0xEC]
def rgb2600(c):
    hue, lum = c >> 4, (c & 0x0e) >> 1
    y = GRAY[lum]
    if hue == 0:
        return y, y, y
    ph = math.radians(316 + (hue - 1) * 24)
    i, q = 60 * math.cos(ph), 60 * math.sin(ph)
    r = y + 0.956 * i + 0.621 * q
    g = y - 0.272 * i - 0.647 * q
    b = y - 1.106 * i + 1.703 * q
    return tuple(max(0, min(255, int(round(v)))) for v in (r, g, b))
pal = ['* GENERATED by tools/gen_gfx.py - 2600 colour byte -> IIgs $0RGB',
       '* index with (colour & $fe): 128 words', 'Pal2600']
for base in range(0, 256, 16):
    words = []
    for c in range(base, base + 16, 2):
        r, g, b = rgb2600(c)
        words.append('$0%X%X%X' % (r >> 4, g >> 4, b >> 4))
    pal.append('                  dw    ' + ','.join(words))
open(os.path.join(ROOT, 'src/gs/pal2600.s'), 'w').write('\n'.join(pal) + '\n')
print('ok: palette table')

# ---- src/gs/lines.s : SHR line tables --------------------------------
BANDS = [(7, 4), (0, 16), (1, 32), (2, 32), (3, 32), (4, 32), (5, 32), (6, 16), (7, 4)]
rowof = []
for row, n in BANDS:
    rowof += [row] * n
assert len(rowof) == 200
ln = ['* GENERATED by tools/gen_gfx.py - SHR line tables',
      '* LineOfs[line] = line*160 ; LineRowOfs[line] = ShrTmpl + row*160']
def words(label, vals, per=8):
    o = []
    for i in range(0, len(vals), per):
        o.append('%-18s dw    %s' % (label if i == 0 else '', ','.join(vals[i:i+per])))
    return o
ln += words('LineOfs', ['%d' % (l * 160) for l in range(200)])
ln += words('LineRowOfs', ['ShrTmpl+%d' % (r * 160) for r in rowof])
ln += hexline('LineRow', rowof)
open(os.path.join(ROOT, 'src/gs/lines.s'), 'w').write('\n'.join(ln) + '\n')
print('ok: line tables')
