#!/usr/bin/env python3
"""The win tune, and the data for the speaker player in src/a2/wintune.s.

  tools/wintune.py gen         write src/a2/winsong.s
  tools/wintune.py wav FILE    render the tune to FILE (what the player does,
                               pass for pass) so it can be heard off-machine
  tools/wintune.py             print the note list with pitches and lengths

The player runs a fixed loop of PASS cycles; each pass steps two 16-bit
phase accumulators, each voice pulses for the first quarter of its
period, and the speaker follows the OR of the two pulses.  A note is
five bytes: length in 256-pass units, then the two accumulator
increments (0 = silent voice).
The song is edited here, in SONG: (beats, voice 1, voice 2).  A voice is
a note name, optionally with cents for detune ("C6+6"), or None.  Every
note ends with a GAP-unit rest so repeated notes separate.
"""
import math, os, struct, sys, wave

CPU = 1020484                # 6502 clock, Hz
PASS = 81                    # cycles a loop pass takes (see wintune.s)
UNIT = 256                   # passes in one length unit
TEMPO = 140                  # beats a minute
GAP = 1                      # units of silence closing every note

RATE = CPU / PASS            # passes a second
UNIT_S = UNIT / RATE         # seconds a unit

# (beats, voice 1, voice 2): a fanfare call, its answer, a rising run,
# and a held chord.  The few cents on a second voice keep it drifting
# against the first, so a held pair shimmers instead of standing still.
SONG = [
    (0.5, 'G4', 'G3'), (0.5, 'G4', 'G3'), (0.5, 'G4', 'G3'), (1.5, 'C5', 'C4+4'),
    (0.5, 'E5', 'C5'), (0.5, 'D5', 'G4'), (0.5, 'E5', 'C5'), (1.5, 'G5', 'C5+4'),
    (0.5, 'F5', 'F4'), (0.5, 'E5', 'C5'), (0.5, 'D5', 'G4'), (0.5, 'C5', 'C4'),
    (0.25, 'C4', None), (0.25, 'E4', None), (0.25, 'G4', None),
    (0.25, 'C5', None), (0.25, 'E5', None), (0.25, 'G5', None),
    (1.0, 'C6', 'G5+4'), (2.0, 'C6', 'C5+5'),
]

NAMES = {'C': 0, 'D': 2, 'E': 4, 'F': 5, 'G': 7, 'A': 9, 'B': 11}

def freq(voice):
    """'G4', 'C6+7' (cents) -> Hz; None -> 0"""
    if voice is None:
        return 0.0
    cents = 0.0
    for i in range(1, len(voice)):
        if voice[i] in '+-':
            voice, cents = voice[:i], float(voice[i:])
            break
    name = voice[0]
    sharp = voice[1] == '#'
    octave = int(voice[1 + sharp:])
    midi = 12 * (octave + 1) + NAMES[name] + sharp
    return 440.0 * 2 ** ((midi - 69 + cents / 100) / 12)

def inc(hz):
    """accumulator increment for a pitch: it wraps 65536 every period"""
    n = int(round(hz * 65536 / RATE))
    assert 0 <= n < 32768, hz
    return n

def notes():
    """-> [(units, inc1, inc2)] with the closing gaps, and the end marker"""
    out = []
    for beats, v1, v2 in SONG:
        units = int(round(beats * 60 / TEMPO / UNIT_S))
        assert GAP < units < 256, (beats, units)
        out.append((units - GAP, inc(freq(v1)), inc(freq(v2))))
        out.append((GAP, 0, 0))
    return out

def render(seq):
    """the player, pass for pass: -> speaker level per pass (+1/-1)"""
    ph1 = ph2 = 0
    last = 0
    level = 1
    out = []
    for units, i1, i2 in seq:
        if not i1:                       # a silent voice parks outside its pulse
            ph1 = 0x8000 | (ph1 & 0xff)
        if not i2:
            ph2 = 0x8000 | (ph2 & 0xff)
        for _ in range(units * UNIT):
            ph1 = (ph1 + i1) & 0xffff
            ph2 = (ph2 + i2) & 0xffff
            bit = 1 if ph1 < 0x4000 or ph2 < 0x4000 else 0
            if bit != last:
                last = bit
                level = -level
            out.append(level)
    return out

def write_wav(path, levels):
    with wave.open(path, 'wb') as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(int(round(RATE)))
        w.writeframes(b''.join(struct.pack('<h', 12000 * v) for v in levels))

if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else 'list'
    seq = notes()
    if cmd == 'gen':
        out = ['* GENERATED by tools/wintune.py - do not edit',
               '* The win tune for PlayWinTune: length in 256-pass units, then the',
               '* two voices\' phase increments (0 = silent).  Length 0 ends it.',
               'WinSong']
        for units, i1, i2 in seq:
            out.append('%-18s%-6s%d,%d,%d,%d,%d' % ('', 'db', units, i1 & 255, i1 >> 8, i2 & 255, i2 >> 8))
        out.append('%-18s%-6s0' % ('', 'db'))
        path = os.path.join(os.path.dirname(__file__), '..', 'src/a2/winsong.s')
        open(path, 'w').write('\n'.join(out) + '\n')
        print('wrote src/a2/winsong.s: %d notes, %.1f s' % (len(SONG), sum(u for u, _, _ in seq) * UNIT_S))
    elif cmd == 'wav':
        write_wav(sys.argv[2], render(seq))
        print('wrote', sys.argv[2])
    else:
        t = 0.0
        for beats, v1, v2 in SONG:
            units = int(round(beats * 60 / TEMPO / UNIT_S))
            print('%6.2fs  %-5s %7.1f Hz   %-5s %7.1f Hz   %3d units' % (t, v1, freq(v1), v2, freq(v2), units))
            t += units * UNIT_S
        print('%6.2fs  end' % t)
