* GENERATED by tools/gen_gfx.py from ref/Adventure.txt - do not edit

* one byte per clock ($ff = pixel on), 8 or 32 bytes per row
SprShrBpr         db    8,8,8,8,8,8,8,8,32,32,8,8,8,8,8,8,8,8,8,8,8,8,8,8
SprShrL           db    <SGfxNull,<SGfxPort01,<SGfxPort02,<SGfxPort03,<SGfxPort04,<SGfxPort05,<SGfxPort06,<SGfxPort07,<SGfxSurround,<SGfxBridge,<SGfxNum1,<SGfxNum2,<SGfxNum3,<SGfxKey,<SGfxBat1,<SGfxBat2,<SGfxDrag0,<SGfxDrag1,<SGfxDrag2,<SGfxSword,<SGfxDot,<SGfxAuthor,<SGfxChalice,<SGfxMagnet
SprShrH           db    >SGfxNull,>SGfxPort01,>SGfxPort02,>SGfxPort03,>SGfxPort04,>SGfxPort05,>SGfxPort06,>SGfxPort07,>SGfxSurround,>SGfxBridge,>SGfxNum1,>SGfxNum2,>SGfxNum3,>SGfxKey,>SGfxBat1,>SGfxBat2,>SGfxDrag0,>SGfxDrag1,>SGfxDrag2,>SGfxSword,>SGfxDot,>SGfxAuthor,>SGfxChalice,>SGfxMagnet
SGfxNull           =     *
SGfxPort01         hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
                   hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
                   hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
                   hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
SGfxPort02         hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
                   hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
                   hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
                   hex   ffffffffffffff00ff00ff00ff00ff00
SGfxPort03         hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
                   hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
                   hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
SGfxPort04         hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
                   hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
                   hex   ffffffffffffff00ff00ff00ff00ff00
SGfxPort05         hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
                   hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
SGfxPort06         hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
                   hex   ffffffffffffff00ff00ff00ff00ff00
SGfxPort07         hex   ffffffffffffff00ff00ff00ff00ff00ffffffffffffff00ff00ff00ff00ff00
SGfxSurround       hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
                   hex   ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
SGfxBridge         hex   ffffffffffffffff00000000000000000000000000000000ffffffffffffffff
                   hex   ffffffffffffffff00000000000000000000000000000000ffffffffffffffff
                   hex   ffffffffffffffff00000000000000000000000000000000ffffffffffffffff
                   hex   ffffffffffffffff00000000000000000000000000000000ffffffffffffffff
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   00000000ffffffff00000000000000000000000000000000ffffffff00000000
                   hex   ffffffffffffffff00000000000000000000000000000000ffffffffffffffff
                   hex   ffffffffffffffff00000000000000000000000000000000ffffffffffffffff
                   hex   ffffffffffffffff00000000000000000000000000000000ffffffffffffffff
                   hex   ffffffffffffffff00000000000000000000000000000000ffffffffffffffff
SGfxNum1           hex   0000000000ff000000000000ffff00000000000000ff00000000000000ff0000
                   hex   0000000000ff00000000000000ff000000000000ffffff00
SGfxNum2           hex   00000000ffffff00000000ff000000ff00000000000000ff000000000000ff00
                   hex   0000000000ff000000000000ff000000000000ffffffffff
SGfxNum3           hex   00000000ffffff00000000ff000000ff00000000000000ff0000000000ffff00
                   hex   00000000000000ff000000ff000000ff00000000ffffff00
SGfxKey            hex   0000000000ffffffffffffffffff00ffff00ff0000ffffff
SGfxBat1           hex   ff000000000000ffff000000000000ffffff00000000ffffffff00000000ffff
                   hex   ffffffffffffffff00ff00ffff00ff0000ffff0000ffff00
SGfxBat2           hex   00000000000000ffff0000000000000000000000000000ffff00000000000000
                   hex   0000ffffffff000000ff00ffff00ff0000ffff0000ffff00ffff00000000ffff
                   hex   ff000000000000ffff000000000000ffff000000000000ff
SGfxDrag0          hex   0000000000ffff0000000000ffffffffffffffff0000ffffffffffffffffff00
                   hex   00000000ffffff000000000000ff00000000000000ff0000000000ffffffff00
                   hex   0000ffffffffffff00ffffffffffffffffffff000000ffffffff00000000ffff
                   hex   ffff00000000ffffffff000000ffffffffffffffffffffff0000ffffffff0000
                   hex   00000000ff000000ff000000ffffffffffffff00000000ff0000ffffffffffff
SGfxDrag1          hex   ff0000000000000000ff0000000000000000ff0000ffff00000000ffffffffff
                   hex   00000000ff00ffff00000000ffffff00000000ffffffff000000ff0000ff0000
                   hex   00ff000000ff0000ff000000ffffff00000000ffffffff000000ffffffffffff
                   hex   00ffffffffffffff00ffffffffffffff00ffffffffffffff00ffffffffffffff
                   hex   0000ffffffffff00000000ffffff000000000000ff000000ffffffffff000000
                   hex   ff00000000000000ffffff0000000000
SGfxDrag2          hex   00000000ffff000000000000ffff000000000000ffff000000000000ffffff00
                   hex   000000ffff00ffff00ffffffffffffffffff0000ffffff00ff00000000000000
                   hex   ffffffffffff0000ffffffffffffff00ffffffffffffff0000ffffffffffff00
                   hex   00ffffffff0000000000ff000000000000ffff00ffffff0000ff00000000ff00
                   hex   00ffffffffffff00
SGfxSword          hex   0000ff000000000000ff000000000000ffffffffffffffff00ff000000000000
                   hex   0000ff0000000000
SGfxDot            hex   ff00000000000000
SGfxAuthor         hex   ffffffff00000000ff00000000000000ff00000000000000ff00000000000000
                   hex   ffffffff00ff00000000000000ff0000ff00000000ffffffffffff0000ff00ff
                   hex   ff00000000ffffffff000000000000000000000000ff00ffffffff0000ff00ff
                   hex   ff00ff0000ffffffffffff00000000ffff00000000ffffffffffff0000000000
                   hex   00000000000000ffffffff0000000000ff00ff0000000000ffffffff00000000
                   hex   00000000000000ff00ff000000000000ffffff000000000000ff000000000000
                   hex   00ff00000000000000ff00000000000000000000000000ffffffff0000000000
                   hex   ff00ff0000000000ffffff0000000000ff00000000000000ffffff0000000000
                   hex   00000000000000ff0000ff00000000000000ff0000000000ffffff0000000000
                   hex   ff00ff0000000000ffffff000000000000000000000000ff00000000000000ff
                   hex   00000000000000ffff000000ff000000ff00ff00ff000000ff00ff00ff000000
                   hex   ff00ff00ff000000ffffffffff00000000000000000000ffffffff0000000000
                   hex   ff00ff0000000000ffffffff0000000000000000000000ffff00000000000000
                   hex   ffffff0000000000ff000000ffffffffff000000ff0000ff00000000ffffffff
                   hex   ff000000ff00ff00ffffff00ff0000ffff00000000000000ff000000ffffff00
                   hex   00000000ff00ff00ffffff00ffffff00ff00ff0000000000ffffff00ff000000
                   hex   ff000000ff000000ffffff00ffffff0000000000ff00ff00ff000000ffffff00
                   hex   ffffff0000000000ff00ff0000ff0000ff00ff0000ff00000000000000ff0000
                   hex   ff0000000000000000000000ff00000000000000ffffff0000000000ff00ff00
                   hex   00000000ff00ff00ff0000000000000000000000ffffff0000000000ff00ff00
                   hex   00000000ffffff0000000000ff00000000000000ffffff00ff00000000000000
                   hex   0000000000ff000000000000ffffff000000000000ff00000000000000ff0000
                   hex   0000000000ff0000ff000000000000000000000000ff000000000000ffffff00
                   hex   0000000000ff00000000000000ff00000000000000ff0000
SGfxChalice        hex   ff000000000000ffff000000000000ffffff00000000ffff00ffffffffffff00
                   hex   00ffffffffffff000000ffffffff0000000000ffff000000000000ffff000000
                   hex   00ffffffffffff00
SGfxMagnet         hex   0000ffffffff000000ffffffffffff00ffffff0000ffffffffff00000000ffff
                   hex   ffff00000000ffffffff00000000ffffffff00000000ffffffff00000000ffff
