* GENERATED by tools/gen_gfx.py - 2600 colour byte -> IIgs $0RGB
* index with (colour & $fe): 128 words
Pal2600
                  dw    $0000,$0444,$0666,$0999,$0BBB,$0CCC,$0DDD,$0EEE
                  dw    $0000,$0440,$0770,$0991,$0BB3,$0DD5,$0EE6,$0FF7
                  dw    $0200,$0630,$0960,$0B82,$0DA4,$0FC6,$0FD7,$0FE8
                  dw    $0300,$0720,$0A53,$0C75,$0E97,$0FB8,$0FCA,$0FDB
                  dw    $0400,$0813,$0B46,$0D68,$0F8A,$0FAB,$0FBD,$0FCE
                  dw    $0402,$0816,$0A49,$0D6B,$0F8D,$0F9F,$0FBF,$0FCF
                  dw    $0305,$0719,$094B,$0C6E,$0E8F,$0F9F,$0FBF,$0FCF
                  dw    $0107,$051B,$084D,$0A6F,$0C8F,$0EAF,$0FBF,$0FCF
                  dw    $0007,$032B,$065E,$087F,$0A9F,$0CBF,$0DCF,$0EDF
                  dw    $0006,$023A,$046D,$078F,$09AF,$0ACF,$0BDF,$0CEF
                  dw    $0005,$0049,$037B,$059E,$07BF,$09DF,$0AEF,$0BFF
                  dw    $0012,$0056,$0289,$04AB,$06CD,$08EE,$09FF,$0AFF
                  dw    $0020,$0063,$0295,$04B8,$06DA,$08EB,$09FC,$0AFD
                  dw    $0020,$0060,$0392,$05B5,$07D7,$08F8,$0AF9,$0BFA
                  dw    $0020,$0160,$0490,$06B2,$08D4,$0AE6,$0BF7,$0CF8
                  dw    $0010,$0350,$0580,$08A1,$0AC3,$0BE5,$0CF6,$0DF7
